### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by athackst** [RobotWebTools/interactive_marker_proxy#2]
Is there a plan to release this into melodic?

**Comment by rctoris** [comment]
I'll try running it this weekend and trigger a release if everything looks good!

**Comment by athackst** [comment]
Great, thanks!

**Comment by dirk-thomas** [comment]
> I'll try running it this weekend and trigger a release if everything looks good!

Any news on this?

**Comment by jihoonl** [comment]
PR is now open. https://github.com/ros/rosdistro/pull/20773
